name: publish

on:
  push:
    branches:
      - gh-pages

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.2.0
          registry-url: https://registry.npmjs.org/

      - name: install hexo
        run: npm i -g hexo-cli
        
      - name: install hexo dependencies
        run: npm i
        
      - name: print local path
        run: pwd && ls -la
      - name: hexo init cmd
        run: hexo init blogs
      - name: after init
        run: cd blogs && ls -la
        

