name: publish

on:
  push:
    branches:
      - gh-pages

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.2.0
          registry-url: https://registry.npmjs.org/

      - name: install hexo
        run: npm i -g hexo-cli
        
      - name: install hexo dependencies
        run: npm i
        
      - name: hexo init cmd
        run: hexo init blogs

      - name: install theme
        run: git clone https://github.com/tufu9441/maupassant-hexo.git themes/maupassant
      
      - name: install render for theme
        run: |
          npm install hexo-renderer-pug --save
          npm install hexo-renderer-sass --save
          
      - name: cp theme config
        run: |
          cp /home/runner/work/myblogs/myblogs/_config.yml /home/runner/work/myblogs/myblogs/blogs/_config.yml
          cp /home/runner/work/myblogs/myblogs/theme_config.yml /home/runner/work/myblogs/myblogs/blogs/themes/_config.yml
        
      - name: cp blog post
        run: cp -r /home/runner/work/myblogs/myblogs/2022 /home/runner/work/myblogs/myblogs/blogs/
      
      - name: ok
        run: echo "happy end"

