name: publish

on:
  push:
    branches:
      - gh-pages

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: 14.2.0
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test

      - name: install hexo-cli
        run: npm i -g hexo-cli
      - run: hexo generate
      - run: echo "******** hello world ********"
