name: publish

on:
  push:
    branches:
      - gh-pages

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: 14.2.0
          registry-url: https://registry.npmjs.org/

      - name: custom operation
        run: |
          npm i -g hexo-cli
          hexo init blogs && cd blogs
          cp ../_config.yml ./_config.yml
          cp ../package.json ./package.json
          cp ../package-lock.json ./package-lock.json
          npm install
          cp -r ../2022 ./source/_posts/
          hexo generate
          ls -la
